### ISSUE TITLE
Weird issue on mobile (iPhone) where each tweet is displayed twice

### ISSUE THREAD

**Issue by AWerchmeister** [jrc03c/visiblepeeps#15]

**Comment by jrc03c** [comment]
I tried it on my Android phone running the Chrome browser and it does it there too.

**Comment by jrc03c** [comment]
But I couldn't replicate it on desktop...

**Comment by jrc03c** [comment]
Has this been sufficiently fixed now?

**Comment by AWerchmeister** [comment]
I think, but let's double check when there aren't deliberate dupes in the database

**Comment by AWerchmeister** [comment]
Seems to be fixed
