### ISSUE TITLE
Categories break when first selecting a category then a level.

### ISSUE THREAD

**Issue by AWerchmeister** [jrc03c/visiblepeeps#32]
If for instance '3D artists' is selected (currently has one tweet) then 'Professional creatives' is selected, only that same tweet is displayed, rather than the 6-7 that has (so far) picked Professional creatives. Additionally, if Show all is selected afterwards, dupes appear of some tweets.

**Comment by jrc03c** [comment]
Right now, the professional levels and the categories operate independently of each other. Both act as a filter on the results. So, if you select "3D artists" and then "hobbyists," you'll only get results that match both of those criteria. I've added an indicator to the menu to show which level and category is currently being viewed. If you want it to work another way, let me know and we can figure it out!

**Comment by jrc03c** [comment]
![screenshot_2018-08-31_08-33-09](https://user-images.githubusercontent.com/255934/44915413-84855e80-acf8-11e8-8553-9f43db6094c4.png)

**Comment by jrc03c** [comment]
Okay, I think I fixed the duplicates problem, too!
