### ISSUE TITLE
Randomize order of tweets?

### ISSUE THREAD

**Issue by jrc03c** [jrc03c/visiblepeeps#36]

**Comment by AWerchmeister** [comment]
I thought they already were :O I seem to get a random order of them anyways :O

**Comment by jrc03c** [comment]
They weren't randomized before, but now they are. However, randomizing them requires getting the _entire_ list of tweets in a category (even though it only "loads" six of them at a time)...which, right now, isn't a big deal network-wise, but could become a problem as we get up towards hundreds of thousands or millions of tweets.
