### ISSUE TITLE
Mobile menu @ top of page, even when far down?

### ISSUE THREAD

**Issue by jrc03c** [jrc03c/visiblepeeps#39]
How hard would it be to make the menu stick at the top of the window instead of at the top of the page? Right now, if a user gets far down the page, they have to scroll all the way back to the top to reach the menu.

**Comment by AWerchmeister** [comment]
I'm gonna try work a different menu solution. Possible one that slides in from the side. The top menu is awkward when it's that long.

**Comment by AWerchmeister** [comment]
The menu scroll isn't smooth like the rest of the site. Not sure what causes this.

**Comment by jrc03c** [comment]
I think I had accidentally caused the menu disappearing bug. It might be fixed now.
