### ISSUE TITLE
Lazyload at Andreas' place is broke.

### ISSUE THREAD

**Issue by AWerchmeister** [jrc03c/visiblepeeps#6]
No errors in the console, but I got this:

`It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.`

The browser also says it's waiting for syndication.twitter.com

**Comment by jrc03c** [comment]
I think this is connected to #5. However, the Firebase message isn't really an error; they're just encouraging developers to use only the parts of the FB library they need instead of loading the whole thing.

**Comment by AWerchmeister** [comment]
fixed
