### ISSUE TITLE
Menu is broken on mobile

### ISSUE THREAD

**Issue by AWerchmeister** [jrc03c/visiblepeeps#8]

**Comment by AWerchmeister** [comment]
I fixed the issue. But we might need to find a better option later.

**Comment by jrc03c** [comment]
Okay, I think I fixed it. Part of the problem (or maybe the whole problem) was that I had accidentally put the menu button inside of the Vue app HTML, and that was interfering (for some reason) with your jQuery stuff. Let me know if it doesn't work for you.

**Comment by jrc03c** [comment]
The problem was actually related to https://stackoverflow.com/a/29940941!

**Comment by jrc03c** [comment]
Fixed with https://github.com/jrc03c/visiblepeeps/commit/ede216ef13e5f2b49c805f30393f55fc2a48a9c9
